export const PUBLISHER_LIST_REQUEST = 'PUBLISHER_LIST_REQUEST'
export const PUBLISHER_LIST_SUCCESS = 'PUBLISHER_LIST_SUCCESS'
export const PUBLISHER_LIST_FAIL = 'PUBLISHER_LIST_FAIL'
export const PUBLISHER_LIST_RESET = 'PUBLISHER_LIST_RESET'

export const PUBLISHER_DELETE_REQUEST = 'PUBLISHER_DELETE_REQUEST'
export const PUBLISHER_DELETE_SUCCESS = 'PUBLISHER_DELETE_SUCCESS'
export const PUBLISHER_DELETE_FAIL = 'PUBLISHER_DELETE_FAIL'