export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST'
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS'
export const REVIEW_CREATE_FAIL = 'REVIEW_CREATE_FAIL'
export const REVIEW_CREATE_RESET = 'REVIEW_CREATE_RESET'

export const SINGLE_PRODUCT_REVIEW_REQUEST = 'SINGLE_PRODUCT_REVIEW_REQUEST'
export const SINGLE_PRODUCT_REVIEW_SUCCESS = 'SINGLE_PRODUCT_REVIEW_SUCCESS'
export const SINGLE_PRODUCT_REVIEW_FAIL = 'SINGLE_PRODUCT_REVIEW_FAIL'
export const SINGLE_PRODUCT_REVIEW_RESET = 'SINGLE_PRODUCT_REVIEW_RESET'